name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6792e910e67428f30a60f0e20b39a0a65771c8f266b88676f004956cd01a422"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
