name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b8be5da606f689067e4ffd40d0211efbaa4ae9e4ac28b8d99437238c48c07e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
