name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "372c55a1f076f74d5de3921975bbdc74978e8d5aea75891cf0f803fa62bf42ee"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
